@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



'hide footbox


participant ":VisitiScheduleController" as CTRL
participant ":visitScheduleRequest" as visit
participant "scheduleRequestRepository:\n ScheduleRequestRepository" as schdlRep
participant ":Repositories" as repositories

autonumber 15
-> CTRL : submitScheduleRequest
autonumber 15.1
activate CTRL

    group Submit Schedule Request



          CTRL -> repositories : getScheduleRequestRepository
          activate repositories

          repositories -> CTRL : scheduleRequestRepository
          deactivate repositories

          CTRL -> schdlRep : getScheduleRequestList (Client)
          activate schdlRep

          schdlRep -> CTRL :
          deactivate schdlRep

    end
    autonumber 16
    <-- CTRL :
deactivate CTRL

@enduml