@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Agency{
    id
    designation
    emailAddress
    phoneNumber
}

class Administrator

class Agent

class Commission{
    typeOfCommission
    commissionValue
}

class StoreManager

class StoreNetworkManager

class Client

class Person{
        name
        passportCardNum
        taxNumber
        emailAddress
        phoneNumber
}

class Owner

class House{
    basement
    inhabitableLoft
    sunExposure
}

class Apartment

class Dwelling{
    numBedrooms
    numBathrooms
    numParkingSpaces
}

class Land

class Equipment

class Property{
    area
    cityCenterDistance
    price
}

class Photograph{
    linkToPhotograph
}

class Employee{

}

class OrganizationRole{
    roleName
}

class Offer{
    publicationDate
}

class Advertisement{
    announcementDate
}

class Visit{
    visitDate
}

class Address{
    street
    cityName
    districtName
    stateAcronym
    zipCode
}

class PropertyType{
    propertyType
}

class Lease{
    leaseValue
    contractDuration
}

class Sale{
    saleValue
}

Address "1" -- "1" Person : located at <
Address "1" -- "1" Agency : located at <

Agency "1" -- "1" StoreManager : manages <
Agency "1" -- "1..*" Employee : owns >

Advertisement "1" -- "1" Property : contains >

OrganizationRole <|-- Administrator
OrganizationRole <|-- Agent
OrganizationRole <|-- StoreManager
OrganizationRole <|-- StoreNetworkManager

OrganizationRole "1..*" -- "1" Employee : plays <

Administrator "1" -- "1..*" Employee : registers >

Client "1" -- "1..*" Property : buys/rents >
Client "1" -- "1..*" Visit : requests >

Owner "1" -- "1..*" Advertisement : makes >

Offer "1" -- "1" Property : contains >

Property "1" -- "1" Address : located at >
Property <|-- Dwelling
Property <|-- Land

Photograph "1..*" -- "1" "Property" : has <

Dwelling "1" -- "1..*" Equipment : has >
Dwelling <|-- Apartment
Dwelling <|-- House

Agent "1" -- "1..*" Advertisement : reviews >
Agent "1" -- "1..*" Offer : publishes >
Agent "1" -- "1..*" Visit : schedules >

Commission "1" -- "1" Agent : defines <

Visit "1" -- "1" Address : located at >

PropertyType "1" -- "1" Property : categorized by <

StoreNetworkManager "1" -- "2..*" Agency : manages >

Owner "1" -- "1..*" Property: sells/rents >
Owner --|> Person

Person <|-- Client
Person <|-- Employee

Lease "0..*" -- "1" Property : classified as <
Lease "1" -- "1..*" Property : classifies >

Sale "0..*" -- "1" Property : classified as <
Sale "1" -- "1..*" Property : classifies >

@enduml