@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Network Manager" as SM
participant ":System" as System

activate SM

    SM -> System : asks to list all deals
    activate System

        System --> SM : asks to select a sort algorithm
    deactivate System

        SM --> System : Choose one of the two sort algorithm
        activate System

        System --> SM : Ask to sort by property \narea (ascending or descending)
        deactivate System

    SM -> System : selects ascending or descending
    activate System

        System --> SM : displays sorted deals
    deactivate System


@enduml