@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



'hide footbox
participant ":BookingRequestController" as CTRL

participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION

autonumber 18
-> CTRL : getAgentNameFromSession()
autonumber 18.1

activate CTRL

    group Get Agent Name

       CTRL -> _APP: getInstance()
       activate _APP
           _APP -> CTRL: appSession
       deactivate _APP

       CTRL -> APP: getCurrentSession()
       activate APP

           APP --> CTRL: currentSession
       deactivate APP

       CTRL -> SESSION: agentName = getUserName()
       activate SESSION

           SESSION --> CTRL: agentName
       deactivate SESSION

    end
    autonumber 19

    <-- CTRL : agentName
deactivate CTRL

@enduml