@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



'hide footbox

participant ":ListDealsController" as CTRL
participant "orderRepository:\nOrderRepository" as OrderRepository

autonumber 7
-> CTRL : getDealsMadeSortedByDate()
autonumber 7.1

activate CTRL

    group Get Deals Made

CTRL -> OrderRepository :  getDealsMadeSortedByDate()
            activate OrderRepository

            OrderRepository --> CTRL : listedDeals
            deactivate OrderRepository

    end
    autonumber 8

    <-- CTRL : ListOfAllDealsMade
deactivate CTRL

@enduml